language: cpp

compiler:
  - clang
  - gcc

before_install:
  # # CMake
  # - sudo add-apt-repository --yes ppa:kalakris/cmake
  # # g++ 4.8
  # - if [ "$CXX" == "g++" ]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test; fi
  # # clang 3.4
  # - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  # - sudo apt-get update -qq

install:
  # CMake
  - sudo apt-get install -qq cmake
  # g++4.8
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # clang 3.6
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.6; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.6"; fi
  # Catch library
  # - curl -o ./lib_external/include/catch.hpp https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp


before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - $CXX --version
  - make && make test
